### ISSUE TITLE
technician is still able to submit another feedback for the same appointment

### ISSUE THREAD

**Issue by Kishen35** [kilat9/oodj-apu-hostel#19]
should they also only be able to submit feedback only once the appointment has been completed?

**Comment by kilat9** [comment]
Actually shouldn't be able to. I was thinking the form closes after giving feedback

**Comment by Kishen35** [comment]
oh yeap it does, just that the way I designed the linking was to open the feedback form after the technician selected one of their upcoming appointments, 
so on that selection page, the appointment still shows and when you select it again, you can still give feedback on it under a new feedback id.
i was thinking i could patch this by only showing appointments which don't have a feedback, but then if I do that, I need to consider also if I should only allow the technician to submit feedback only once their appointment has been completed (like only allow to provide feedback after the date and slot of the appointment)

**Comment by Kishen35** [comment]
resolved with #25
