### ISSUE TITLE
new-user-data-order still not exactly in order

### ISSUE THREAD

**Issue by Kishen35** [kilat9/oodj-apu-hostel#23]
need your help jo, customer has been done nicely, but center technician and center manager are still little out of place

**Reference**
![image](https://user-images.githubusercontent.com/14159195/149261833-8e3d9b22-40f9-460e-ba2c-7368ec908b88.png)

**Center Manager**

- [x] remove CM
- [x] put password before dateCreated

![image](https://user-images.githubusercontent.com/14159195/149261747-509f0713-749c-485c-bd51-8f5d874add96.png)

**Center Technician**

- [x] remove CT
- [x] put password, pay grade and then only dateCreated

![image](https://user-images.githubusercontent.com/14159195/149261929-8e333e5a-fe90-448a-a30f-df6a7e4dbe10.png)

**Comment by kilat9** [comment]
Alright will fix it

**Comment by kilat9** [comment]
Fixed

**Comment by Kishen35** [comment]
thanks for fixing, but i think you now need to change the code for pLogin also, 
cause now for example, centerTechnician, it takes date as the password
and login for centerManager returns an Index out of bounds error

**Comment by Kishen35** [comment]
fixed with #24
